version: "3.3"

services:
  player:
    build: ./player
    ports:
      - 5000:5000
  lobby:
    build: ./lobby
    ports:
      - 5001:5000
  game:
    build: ./game
    ports:
      - 5002:5000
  word:
    build: ./word
    ports:
      - 5003:5000
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
